google/pdl

.gitignore
Cargo.toml

The crate name pdl is already taken on crates.io.

Change the package name to pdl-compiler and the default binary to pdlc

---

.github/workflows/build.yml

The `push` trigger is enough when people open PRs via branches in this repository. However, since we hope to get contributions via forks, we need to trigger on `pull_request` synchronization too.

Trigger builds when PRs are synchronized

---

.github/workflows/build.yml

This should make it easy to trigger builds via the web interface, see the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).

Allow build workflow to be run via `workflow_dispatch`

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/backends_json_generate.rs
fuzz/fuzz_targets/backends_rust_generate.rs
src/lib.rs
src/main.rs

This PR adds fuzz targets for the JSON and Rust backends.
The JSON backend is very small and basically glues existing libraries together. As such, it's the one that should "just work" and so far, it seems solid.
The Rust backend is full of our own code and the fuzzer there immediately found two small bugs: #32 and #33.
We can work on enabling the fuzzer when they're a bit more stable.

Add fuzz testing targets

---

scripts/generate_cxx_backend.py
scripts/generate_cxx_backend_tests.py
scripts/packet_runtime.h

- Rename Serialize -> SerializeToBytes
The compiler is unable to resolve to serialize
because of its overloading virtual namesake
- Rename ASSERT -> _ASSERT_VALID to prevent
clashes with definitions in external headers

Update CXX runtime and generator

---

scripts/generate_cxx_backend.py

Otherwise generates a compiler error if multiple generated headers
are included in the same source.

Generate _ASSERT_VALID under a guard

---

src/backends/rust/parser.rs
tests/generated/packet_decl_24bit_enum_array_big_endian.rs
tests/generated/packet_decl_24bit_enum_array_little_endian.rs
tests/generated/packet_decl_24bit_enum_big_endian.rs
tests/generated/packet_decl_24bit_enum_little_endian.rs
tests/generated/packet_decl_64bit_enum_array_big_endian.rs
tests/generated/packet_decl_64bit_enum_array_little_endian.rs
tests/generated/packet_decl_64bit_enum_big_endian.rs
tests/generated/packet_decl_64bit_enum_little_endian.rs
tests/generated/packet_decl_8bit_enum_array_big_endian.rs
tests/generated/packet_decl_8bit_enum_array_little_endian.rs
tests/generated/packet_decl_8bit_enum_big_endian.rs
tests/generated/packet_decl_8bit_enum_little_endian.rs
tests/generated/packet_decl_child_packets_big_endian.rs
tests/generated/packet_decl_child_packets_little_endian.rs
tests/generated/packet_decl_fixed_enum_field_big_endian.rs
tests/generated/packet_decl_fixed_enum_field_little_endian.rs
tests/generated/packet_decl_fixed_scalar_field_big_endian.rs
tests/generated/packet_decl_fixed_scalar_field_little_endian.rs
tests/generated/packet_decl_grand_children_big_endian.rs
tests/generated/packet_decl_grand_children_little_endian.rs
tests/generated/packet_decl_mixed_scalars_enums_big_endian.rs
tests/generated/packet_decl_mixed_scalars_enums_little_endian.rs
tests/generated/packet_decl_parent_with_alias_child_big_endian.rs
tests/generated/packet_decl_parent_with_alias_child_little_endian.rs
tests/generated/packet_decl_parent_with_no_payload_big_endian.rs
tests/generated/packet_decl_parent_with_no_payload_little_endian.rs

The invalid enum value is read a second time to generate the
error message when read as a bitfield. This is invalid
as reading potentially consumes the input bytes.

Fix double read of invalid enum values

---

src/analyzer.rs
src/ast.rs
src/backends/rust.rs
src/parser.rs
tests/generated/enum_declaration_big_endian.rs
tests/generated/enum_declaration_little_endian.rs

Open enums describe enums that accept unknown
values in the parsing phase. The unknown values are
reported to the user using a default tag if the
language constrains enum types.
Enums are declared open by defining the default
tag using the syntax A = ..

Implement support for open enums

---

doc/rust-generated-code-guide.rst
src/backends/rust.rs
src/backends/rust/parser.rs
src/backends/rust/serializer.rs
src/backends/rust/types.rs
tests/generated/reserved_identifier_big_endian.rs
tests/generated/reserved_identifier_little_endian.rs

Append '_' to the identifiers. e.g. 'type' is renamed to 'type_'.

Rname identifiers that match rust reserved keyword list

---

scripts/generate_cxx_backend.py
src/backends/rust/parser.rs
tests/generated/packet_decl_fixed_scalar_field_big_endian.rs
tests/generated/packet_decl_fixed_scalar_field_little_endian.rs

- Generate forward declarations for packet view classes
- Value of fixed value field may be read twice from the input buffer

double read

---

scripts/generate_cxx_backend.py

The packet views use friend class declarations to
allow access to parent fields; some compilers do not
resolve the friend declarations if the class is not in
scope.

Generate forward declarations for packet view classes

---

pdl-derive/src/lib.rs

Source pdl files are expected as relative paths from
the cargo manifest dir

pdl-derive: Remove src/ from the list of searched paths

---

pdl-compiler/scripts/generate_python_backend.py
pdl-compiler/scripts/pdl/core.py

The following pattern is missing constraint validation in the generated
code:
```
packet A {
a: 8,
b: 8,
_payload_,
}
packet B : A (a = 1) {
_payload_,
}
packet C : B (b = 1) {}
packet D : B (b = 2) {}
```
The constraint a == 1 is not validated in either C or D

python: Generate missing constraint validation for traversed children

---

pdl-compiler/src/backends/rust.rs
pdl-compiler/src/backends/rust/parser.rs
pdl-compiler/src/backends/rust/serializer.rs
pdl-compiler/src/bin/generate-canonical-tests.rs
pdl-compiler/tests/generated/payload_with_size_modifier_big_endian.rs
pdl-compiler/tests/generated/payload_with_size_modifier_little_endian.rs
pdl-compiler/tests/run_rust_generator_tests.sh

Fixes #83
Enables the following declaration in the
rust generator.
```
struct Test {
_size_(_payload_) : 8,
_payload_ : [+2],
}
```

Implement support for payload field size modifiers

---

pdl-compiler/src/backends/intermediate.rs
pdl-compiler/src/backends/rust_no_allocation/mod.rs
pdl-compiler/src/lib.rs

Having non-deterministic generated sources means that incremental builds would have extra recompilations.
Also pretty-print the generated code.
The non-determinism was discovered in some android modules like [bluetooth_core_rust_packets](https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/system/rust/Android.bp;l=195;drc=d9229010d8557c06c0a09d44f8fb201fef715cc7)

Make the rust_no_allocation backend deterministic

---

doc/python-generated-code-guide.rst
pdl-compiler/scripts/generate_cxx_backend.py
pdl-compiler/scripts/generate_python_backend.py
pdl-compiler/scripts/pdl/core.py
pdl-compiler/src/bin/generate-canonical-tests.rs
pdl-compiler/tests/canonical/le_test_file.pdl
pdl-compiler/tests/canonical/le_test_vectors.json
pdl-compiler/tests/python_generator_test.py

- previously generated tags x_START and x_END for tag ranges,
but IntEnum declarations are closed so parsing a value
in these ranges would fail
- instead removed declaration for range bounds,
and relax the generated code to use
Union[IntEnum, int] instead of IntEnum
- provide IntEnum.from_int to validate values to are not
matched to tags, that they are correctly inside of the
ranges

Improve support for open enums in generated pytnon

---

pdl-compiler/src/backends/rust/mod.rs
pdl-compiler/tests/generated/rust/custom_field_declaration_big_endian.rs
pdl-compiler/tests/generated/rust/custom_field_declaration_little_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_custom_field_big_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_custom_field_little_endian.rs

The PDL source
```
custom_field Test : 32 "test"
```
will now generate impl Packet
```
pub struct Test(u32);
impl Packet for Test {
}
```

Implement Packet trait for custom fields of constant size

---

pdl-compiler/src/backends/rust/mod.rs

error: unnecessary use of `get(f.id().unwrap()).is_none()`
--> pdl-compiler/src/backends/rust/mod.rs:93:37
|
93 |         .filter(|f| all_constraints.get(f.id().unwrap()).is_none())
|                     ----------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|                     |
|                     help: replace it with: `!all_constraints.contains_key(f.id().unwrap())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_get_then_check
= note: `-D clippy::unnecessary-get-then-check` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_get_then_check)]`
error: unnecessary use of `get(f.id().unwrap()).is_some()`
--> pdl-compiler/src/backends/rust/mod.rs:111:37
|
111 |         .filter(|f| …

Fix unnecessary-get-then-check clippy warning

---

pdl-compiler/src/backends/rust/parser.rs
pdl-compiler/src/backends/rust/serializer.rs

The legacy rust generator did not support derived structs because of
lack of common interface for parsing packets.
All packets under the new generator implement Packet::decode which
make it trivial to support.

Allow derived structs in packets in new rust generator

---

Cargo.toml
pdl-derive/src/lib.rs
pdl-tests/Cargo.toml
pdl-tests/tests/specialize.rs

Tests are added to the crate pdl-tests, which implements a
private proc_macro pdl! that generates a rust module from
an inline PDL grammar.
The tests are added following this pattern:
```
// inline pdl grammar to be tested
"#)]
mod test_module {
#[test]
fn test_one() {
}
// more tests
}
```

Write unit tests for the rust generator

---

pdl-compiler/scripts/generate_python_backend.py
pdl-compiler/src/backends/rust/mod.rs
pdl-derive/tests/examples.rs

The generated code for the following was incorrect and stopped
parsing at the first element:
```
struct Inner {
_size_(value): 8,
value: 8[],
}
struct Outer {
elements: Inner[],
}
```

Fix python generation error for dynamic-element size arrays

---

pdl-compiler/src/analyzer.rs
pdl-compiler/src/ast.rs
pdl-compiler/src/backends/rust/encoder.rs
pdl-compiler/src/backends/rust_legacy/serializer.rs
pdl-runtime/src/lib.rs
pdl-tests/tests/semantic.rs

I've got the following usecase requiring me to use `if` twice
```
tx_timestamp_length : 1,
tx_timestamp_40: 40 if tx_timestamp_length = 0,
tx_timestamp_64: 64 if tx_timestamp_length = 1,
```
Right now `check_optional_fields` disallows this while it's working perfectly fine.
This PR removes the check and allows the use of an `if` condition.

optional: allow duplicate if statements

---

pdl-compiler/Cargo.toml
pdl-runtime/Cargo.toml

For pdl-compiler:
heck 0.4.0 -> 0.4.1
proc-macro2 1.0.46 -> 1.0.75
quote 1.0.21 -> 1.0.36
serde_json 1.0.86 -> 1.0.94
argh 0.1.7 -> 0.1.12
syn 2.0.16 -> 2.0.58
prettyplease 0.2.6 -> 0.2.17
For pdl-runtime
bytes 1.4.0 -> 1.7.2
thiserror 1.0.47 -> 1.0.49

Update crate dependency version to match AOSP crates

---

pdl-compiler/src/analyzer.rs
pdl-compiler/src/backends/rust/decoder.rs
pdl-compiler/src/backends/rust/encoder.rs
pdl-compiler/src/backends/rust/mod.rs
pdl-compiler/src/backends/rust_legacy/parser.rs
pdl-compiler/src/backends/rust_legacy/serializer.rs
pdl-compiler/src/parser.rs
pdl-compiler/tests/generated/rust/packet_decl_grand_children_big_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_grand_children_little_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_parent_with_alias_child_big_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_parent_with_alias_child_little_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_parent_with_no_payload_big_endian.rs
pdl-compiler/tests/generated/rust/packet_decl_parent_with_no_payload_little_endian.rs
pdl-compiler/tests/generated/rust/struct_decl_grand_children_big_endian.rs
pdl-compiler/tests/generated/rust/struct_decl_grand_children_little_endian.rs
pdl-derive/Cargo.toml
pdl-tests/Cargo.toml
pdl-tests/tests/specialize.rs

- **Split the decl and parent size in the schema**
- **Refine the specialize() implementation of the rust backend**

rust fixup
